services:
  web:
    build:
        context: ./CrosswordHelper.Web/crossword-helper
    ports:
      - 4202:4200
  api:
    build: .
    environment:
      - ConnectionStrings__crosswordHelper=User Id=user;Password=password;Host=host.docker.internal;Port=5432;Database=crossword_helper
    ports:
      - "8080:8080"
  db:
    image: db
    container_name: db
    build:
      context: ./Database
      dockerfile: ./Deploy/Dockerfile
      target: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432